name: wscd
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10.11
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - libffi=3.4.4
  - openssl=1.1.1t
  - pip=23.0.1
  - setuptools=66.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pytorch-cuda=11.7.0
  - pytorch=1.12.0
  - torchvision=0.13.0

  - pip:
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cycler==0.11.0
      - docker-pycreds==0.4.0
      - fonttools==4.39.4
      - gitdb==4.0.10
      - gitpython==3.1.31
      - idna==3.4
      - imageio==2.28.1
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - matplotlib==3.5.2
      - networkx==3.1
      - numpy==1.24.3
      - opencv-python==4.7.0.72
      - packaging==23.1
      - pathtools==0.1.2
      - pillow==9.5.0
      - promise==2.3
      - protobuf==3.20.3
      - psutil==5.9.5
      - pycocotools==2.0.4
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pywavelets==1.4.1
      - pyyaml==6.0
      - requests==2.30.0
      - scikit-image==0.19.3
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - selective-search==1.1.0
      - sentry-sdk==1.23.1
      - setproctitle==1.3.2
      - shortuuid==1.0.11
      - six==1.16.0
      - smmap==5.0.0
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - torchmetrics==0.9.2
      - tqdm==4.64.0
      - ttach==0.0.3
      - typing-extensions==4.5.0
      - urllib3==1.26.15
      - wandb==0.12.21
